# ---------- Stage 1: Build React App ----------
ARG NODE_VERSION=18
FROM node:${NODE_VERSION}-alpine AS build

WORKDIR /app

# copy dependency files first (for caching)
COPY package*.json ./
RUN npm install

# copy source code
COPY . .

# build production static files
RUN npm run build


# ---------- Stage 2: Serve using Nginx ----------
FROM nginx:alpine

# remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# copy built files from previous stage
COPY --from=build /app/build /usr/share/nginx/html

# expose web port
EXPOSE 80

# start nginx
CMD ["nginx", "-g", "daemon off;"]


